import type { Metadata } from "next";
// Import semua font yang dibutuhkan
import { Geist, Geist_Mono } from "next/font/google";
import { Poppins, Inter } from 'next/font/google';
import "./globals.css";

// 1. Konfigurasi Font Geist (Tetap Dipertahankan)
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// 2. Konfigurasi Font Poppins (Untuk Heading)
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600', '700', '800', '900'],
  variable: '--font-heading',
});

// 3. Konfigurasi Font Inter (Untuk Body)
const inter = Inter({
  subsets: ['latin'],
  variable: '--font-body',
});

// Metadata tetap sama
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 4. SATU-SATUNYA RootLayout Component
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html 
        lang="en" 
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} ${inter.variable}`}
    >
      <body className={`antialiased`}>
        {children}
      </body>
    </html>
  );
}
